display:
  default:
    display_options:
      fields:
        status:
          label: Estado
      filters:
        status:
          group_info:
            label: Estado
        permission:
          expose:
            label: Permiso
