display:
  default:
    display_options:
      fields:
        bundle:
          label: Tipo
        status:
          label: Estado
      filters:
        bundle:
          expose:
            label: Tipo
