display:
  default:
    display_options:
      fields:
        status:
          label: Estado
      filters:
        status:
          expose:
            label: Estado
  page_2:
    display_options:
      fields:
        entity_label:
          label: Entidad
