display:
  default:
    display_options:
      fields:
        status:
          label: Estado
        count:
          label: 'Usado en'
      filters:
        status:
          expose:
            label: Estado
  page_2:
    display_options:
      fields:
        entity_label:
          label: Entidad
        type:
          label: 'Tipo de entidad'
