label: 档案
display:
  default:
    display_title: 主
    display_options:
      exposed_form:
        options:
          submit_button: 应用
          reset_button_label: 重置
          exposed_sorts_label: 排序依据
          sort_asc_label: 升序
          sort_desc_label: 降序
      arguments:
        uid:
          exception:
            title: 全部
        type:
          exception:
            title: 全部
        status:
          exception:
            title: 全部
      title: 档案
  user_page:
    display_title: 用户页面
