minimum_single: 20
minimum_multiple: 20
disable_search_threshold: 0
minimum_width: 0
use_relative_width: false
jquery_selector: 'select:visible'
search_contains: true
disable_search: false
allow_single_deselect: false
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
max_shown_results: null
disabled_themes:
  claro: '0'
  bootstrap_barrio: '0'
  uspshrdemo: '0'
chosen_include: 2
_core:
  default_config_hash: exRaKE0s6uZbfQrl_2WFEcTlc_1t81xEqCLuCCteUSk
