module:
  actions_permissions: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  autologout: 0
  automated_cron: 0
  ban: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_blacklist: 0
  block_class: 0
  block_content: 0
  block_content_permissions: 0
  block_user_info: 0
  breakpoint: 0
  captcha: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_direct_save: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  eck: 0
  editor: 0
  embed: 0
  entity: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_enhanced: 0
  entity_browser_entity_form: 0
  entity_browser_example: 0
  entity_clone: 0
  entity_embed: 0
  entity_reference_revisions: 0
  facets: 0
  feeds: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  gnode: 0
  google_analytics: 0
  group: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inline_entity_form: 0
  language: 0
  layout_builder: 0
  layout_builder_restrictions: 0
  layout_builder_styles: 0
  layout_discovery: 0
  layout_library: 0
  layout_section_classes: 0
  link: 0
  link_attributes: 0
  locale: 0
  login_security: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_ui: 0
  message: 0
  message_ui: 0
  metatag: 0
  metatag_views: 0
  moderation_dashboard: 0
  node: 0
  node_view_permissions: 0
  options: 0
  override_node_options: 0
  page_cache: 0
  page_manager: 0
  panels: 0
  paragraph_blocks: 0
  path: 0
  path_alias: 0
  private_message: 0
  profile: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_tokens: 0
  purge_ui: 0
  quickedit: 0
  r4032login: 0
  rdf: 0
  realname: 0
  redirect: 0
  redirect_404: 0
  rest: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_pantheon: 0
  search_api_solr: 0
  search_autocomplete: 0
  serialization: 0
  settings_tray: 0
  shariff: 0
  shortcut: 0
  sitemap: 0
  smtp: 0
  superfish: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  toolbar_anti_flicker: 0
  tour: 0
  update: 0
  user: 0
  usps_hr: 0
  video_embed_field: 0
  views_autocomplete_api: 0
  views_bulk_operations: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  claro: 0
  bootstrap_barrio: 0
  uspshrdemo: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
