excluded_entities: 'block,block_content_type,block_content,comment_type,contact_form,contact_message,editor,field_storage_config,field_config,field_collection,field_collection_item,file,filter_format,image_style,login_destination,link_configuration_storage,rdf_mapping,rest_resource_config,search_page,shortcut,shortcut_set,action,menu,tour,user_role,menu_link_content,view,entity_form_display,entity_form_mode,entity_view_display,entity_view_mode,date_format,base_field_override'
_core:
  default_config_hash: 47YWQALbm33aanLQkeJc91MpPqhtslI3nQG4wCOJrnk
user_enable: 'Create,Update,Delete'
user_noti_create_message: 'User has been created by [user:name]'
user_noti_update_message: 'User has been updated by [user:name]'
user_noti_delete_message: 'User has been deleted by [user:name]'
user_redirect_create_link: '[entity:url]'
user_redirect_update_link: '[entity:url]'
user_redirect_delete_link: '[entity:url]'
article_enable: 'Create,Update,Delete'
article_noti_create_message: 'Article has been created by [user:name]'
article_noti_update_message: 'Article has been updated by [user:name]'
article_noti_delete_message: 'Article has been deleted by [user:name]'
article_redirect_create_link: '[entity:url]'
article_redirect_update_link: '[entity:url]'
article_redirect_delete_link: '[entity:url]'
blog_post_enable: 'Create,Update,Delete'
blog_post_noti_create_message: 'Blog Post has been created by [user:name]'
blog_post_noti_update_message: 'Blog Post has been updated by [user:name]'
blog_post_noti_delete_message: 'Blog Post has been deleted by [user:name]'
blog_post_redirect_create_link: '[entity:url]'
blog_post_redirect_update_link: '[entity:url]'
blog_post_redirect_delete_link: '[entity:url]'
entity_browser_test_enable: 'Create,Update,Delete'
entity_browser_test_noti_create_message: 'Entity browser test has been created by [user:name]'
entity_browser_test_noti_update_message: 'Entity browser test has been updated by [user:name]'
entity_browser_test_noti_delete_message: 'Entity browser test has been deleted by [user:name]'
entity_browser_test_redirect_create_link: '[entity:url]'
entity_browser_test_redirect_update_link: '[entity:url]'
entity_browser_test_redirect_delete_link: '[entity:url]'
forms_enable: 'Create,Update,Delete'
forms_noti_create_message: 'Forms has been created by [user:name]'
forms_noti_update_message: 'Forms has been updated by [user:name]'
forms_noti_delete_message: 'Forms has been deleted by [user:name]'
forms_redirect_create_link: '[entity:url]'
forms_redirect_update_link: '[entity:url]'
forms_redirect_delete_link: '[entity:url]'
hr_announcement_enable: 'Create,Update,Delete'
hr_announcement_noti_create_message: 'Announcement has been created by [user:name]'
hr_announcement_noti_update_message: 'Announcement has been updated by [user:name]'
hr_announcement_noti_delete_message: 'Announcement has been deleted by [user:name]'
hr_announcement_redirect_create_link: '[entity:url]'
hr_announcement_redirect_update_link: '[entity:url]'
hr_announcement_redirect_delete_link: '[entity:url]'
hr_event_enable: 'Create,Update,Delete'
hr_event_noti_create_message: 'Event has been created by [user:name]'
hr_event_noti_update_message: 'Event has been updated by [user:name]'
hr_event_noti_delete_message: 'Event has been deleted by [user:name]'
hr_event_redirect_create_link: '[entity:url]'
hr_event_redirect_update_link: '[entity:url]'
hr_event_redirect_delete_link: '[entity:url]'
hr_landing_page_enable: 'Create,Update,Delete'
hr_landing_page_noti_create_message: 'Landing Page has been created by [user:name]'
hr_landing_page_noti_update_message: 'Landing Page has been updated by [user:name]'
hr_landing_page_noti_delete_message: 'Landing Page has been deleted by [user:name]'
hr_landing_page_redirect_create_link: '[entity:url]'
hr_landing_page_redirect_update_link: '[entity:url]'
hr_landing_page_redirect_delete_link: '[entity:url]'
hr_media_gallery_enable: 'Create,Update,Delete'
hr_media_gallery_noti_create_message: 'Media Gallery has been created by [user:name]'
hr_media_gallery_noti_update_message: 'Media Gallery has been updated by [user:name]'
hr_media_gallery_noti_delete_message: 'Media Gallery has been deleted by [user:name]'
hr_media_gallery_redirect_create_link: '[entity:url]'
hr_media_gallery_redirect_update_link: '[entity:url]'
hr_media_gallery_redirect_delete_link: '[entity:url]'
hr_topic_enable: 'Create,Update,Delete'
hr_topic_noti_create_message: 'Topic has been created by [user:name]'
hr_topic_noti_update_message: 'Topic has been updated by [user:name]'
hr_topic_noti_delete_message: 'Topic has been deleted by [user:name]'
hr_topic_redirect_create_link: '[entity:url]'
hr_topic_redirect_update_link: '[entity:url]'
hr_topic_redirect_delete_link: '[entity:url]'
page_enable: 'Create,Update,Delete'
page_noti_create_message: 'Basic page has been created by [user:name]'
page_noti_update_message: 'Basic page has been updated by [user:name]'
page_noti_delete_message: 'Basic page has been deleted by [user:name]'
page_redirect_create_link: '[entity:url]'
page_redirect_update_link: '[entity:url]'
page_redirect_delete_link: '[entity:url]'
comment_enable: 'Create,Update,Delete'
comment_noti_create_message: ' comments has been created by [user:name]'
comment_noti_update_message: ' comments has been updated by [user:name]'
comment_noti_delete_message: ' comments has been deleted by [user:name]'
comment_redirect_create_link: '[entity:url]'
comment_redirect_update_link: '[entity:url]'
comment_redirect_delete_link: '[entity:url]'
category_enable: 'Create,Update,Delete'
category_noti_create_message: 'Category has been created by [user:name]'
category_noti_update_message: 'Category has been updated by [user:name]'
category_noti_delete_message: 'Category has been deleted by [user:name]'
category_redirect_create_link: '[entity:url]'
category_redirect_update_link: '[entity:url]'
category_redirect_delete_link: '[entity:url]'
form_categories_enable: 'Create,Update,Delete'
form_categories_noti_create_message: 'Form Categories has been created by [user:name]'
form_categories_noti_update_message: 'Form Categories has been updated by [user:name]'
form_categories_noti_delete_message: 'Form Categories has been deleted by [user:name]'
form_categories_redirect_create_link: '[entity:url]'
form_categories_redirect_update_link: '[entity:url]'
form_categories_redirect_delete_link: '[entity:url]'
tags_enable: 'Create,Update,Delete'
tags_noti_create_message: 'Tags has been created by [user:name]'
tags_noti_update_message: 'Tags has been updated by [user:name]'
tags_noti_delete_message: 'Tags has been deleted by [user:name]'
tags_redirect_create_link: '[entity:url]'
tags_redirect_update_link: '[entity:url]'
tags_redirect_delete_link: '[entity:url]'
notfication_widget_conf: 1
additional_entity_type: ''
