shariff_css: complete
shariff_theme: colored
shariff_orientation: horizontal
shariff_services:
  twitter: twitter
  facebook: facebook
_core:
  default_config_hash: QaBP0FEBQFVu_6eshMIR_MgA6mVmi5AeVqtHIYSzXNw
