data_source: null
roles_to_geolocate:
  authenticated: authenticated
save_user_location_creation: true
roles_in_debug_mode:
  admin: false
  anonymous: false
  authenticated: false
roles_in_debug_mode_ip:
  admin: null
  anonymous: null
  authenticated: null
allowed_pages: null
excluded_ips: null
eu_visitor_dont_save: false
timezone_format: identifier
_core:
  default_config_hash: shw4iv2Lr5GoD_YlLlPuo621mnZN7b4SZJVcphJ-G54
